spring.datasource.url=jdbc:postgresql://localhost:5432/content?currentSchema=contentModule
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=contentModule
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jpa.compliance.entity_manager_factory_interface=jakarta.persistence.EntityManagerFactory

server.port=8080

motorsports.api.key=a3344a18efmsh1df8778ab3f8611p13f0d9jsn9d5e72743ec2
