# Existing configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/user?currentSchema=usermodule
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=usermodule
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
logging.level.org.springframework.security=DEBUG

server.port=8080

# OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=833562189502-n8kp47ika5p00l3a5js1gctbt7ec7bkl.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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